sudo: required

language: python
python:
    - "3.4"
#   - "3.5"
#   - "3.5-dev"
#   - "nightly"

# test dockerization
services:
    - docker

script:
    - sudo ./manage-docker.sh up
    - sleep 2
    - sudo docker ps -a
    - diff -q <(sudo ./manage-docker.sh port) <(echo "80/tcp -> 0.0.0.0:80") >/dev/null  # test if container runs
# test website; maybe we want to run unittests here later
# TODO run some tests...
