sudo: required

language: python
python:
    - "3.4"
#   - "3.5"
#   - "3.5-dev"
#   - "nightly"

# test dockerization
services:
    - docker

before_install:
    - git submodule foreach git submodule init
    - git submodule foreach git submodule update

script:
    - sudo ./manage-docker.sh up
    - sleep 10  # wait until post_setup is done
    - sudo docker ps -a
    - sudo ./manage-docker.sh port
    - sudo docker logs fablab_website
    - diff -q <(sudo ./manage-docker.sh port) <(echo "80/tcp -> 0.0.0.0:80") >/dev/null  # test if container runs
# test website; maybe we want to run unittests here later
# TODO run some tests...
